name = "status-axolotlpower-com-workers"
main = "src/index.js"
compatibility_date = "2023-05-18"

[triggers]
crons = ["*/2 * * * *"]

[[kv_namespaces]]
binding = "STATUS_INFO"
id = "b9054efdd25d46cfb8bc8b805f9816c0"


[placement]
mode = "smart"
